export const GET_MENU = 'GET_MENU';

export const GET_MENU_CAT = 'GET_MENU_CAT';
export const GET_MENU_CAT_RECOMMENDED = 'GET_MENU_CAT_RECOMMENDED';
export const GET_MENU_CAT_MOST_FAVORITE = 'GET_MENU_CAT_MOST_FAVORITE';
export const GET_MENU_CAT_APPETIZER = 'GET_MENU_CAT_APPETIZER';
export const GET_MENU_CAT_HOT_DISHES = 'GET_MENU_CAT_HOT_DISHES';
export const GET_MENU_CAT_SEAFOOD = 'GET_MENU_CAT_SEAFOOD';
export const GET_MENU_CAT_VEGETABLE = 'GET_MENU_CAT_VEGETABLE';
export const GET_MENU_CAT_STAPLE = 'GET_MENU_CAT_STAPLE';

export const GET_MENU_DETAIL = 'GET_MENU_DETAIL';

export const ADD_TO_CART = 'ADD_TO_CART';

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
